Mox.defmock(Fermo.BuildMock, for: Fermo.Build)
Mox.defmock(Fermo.ConfigMock, for: Fermo.Config)
Mox.defmock(Fermo.CompilerMock, for: Fermo.Compiler)
Mox.defmock(Fermo.FileMock, for: Fermo.File)
Mox.defmock(Fermo.I18nMock, for: Fermo.I18n)
Mox.defmock(Fermo.LocalizableMock, for: Fermo.Localizable)
Mox.defmock(Fermo.PaginationMock, for: Fermo.Pagination)
Mox.defmock(Fermo.SimpleMock, for: Fermo.Simple)
Mox.defmock(Fermo.SitemapMock, for: Fermo.Sitemap)
Mox.defmock(Fermo.TemplateMock, for: Fermo.Template)
Mox.defmock(Mix.Fermo.Compiler.ManifestMock, for: Mix.Fermo.Compiler.Manifest)

Mox.defmock(FileMock, for: FileBehaviour)
Mox.defmock(Mix.UtilsMock, for: Mix.UtilsBehaviour)
